name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:

  install:


  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      run: go get -u golang.org/x/lint/golint

    - name: Lint
      run: make lint
#    - name: Build
 #     run: go build -v ./...

  #  - name: Test
   #   run: go test -v ./...

