name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Lint
      run: make lint

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make

  deploy:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "Dockerfile,build,config_prod.json"
        target: "/root/lamboWorkshop/lamboTrunk"
