name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Lint
      run: make lint

  build:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make prod

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        if_key_exists: ignore
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: |
       rsync -avz build Dockerfile config_prod.json root@${{ secrets.SSH_HOST }}:/root/lamboWorkshop/lamboTrunk
       ssh root@{{ secrets.SSH_HOST }} << EOF
       docker-compose up -d --build --force-recreate --no-deps database
       EOF

